//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFMentorshipProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFMentorshipProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to American.
        /// </summary>
        internal static string AmericanNationality {
            get {
                return ResourceManager.GetString("AmericanNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Argentina.
        /// </summary>
        internal static string ArgentinaFederation {
            get {
                return ResourceManager.GetString("ArgentinaFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argentine.
        /// </summary>
        internal static string ArgentineNationality {
            get {
                return ResourceManager.GetString("ArgentineNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australian.
        /// </summary>
        internal static string AustralianNationality {
            get {
                return ResourceManager.GetString("AustralianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Austrian.
        /// </summary>
        internal static string AustrianNationality {
            get {
                return ResourceManager.GetString("AustrianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belarusian.
        /// </summary>
        internal static string BelarusianNationality {
            get {
                return ResourceManager.GetString("BelarusianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgian.
        /// </summary>
        internal static string BelgianNationality {
            get {
                return ResourceManager.GetString("BelgianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bolivian.
        /// </summary>
        internal static string BolivianNationality {
            get {
                return ResourceManager.GetString("BolivianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Brazil.
        /// </summary>
        internal static string BrazilFederation {
            get {
                return ResourceManager.GetString("BrazilFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brazilian.
        /// </summary>
        internal static string BrazilianNationality {
            get {
                return ResourceManager.GetString("BrazilianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulgarian.
        /// </summary>
        internal static string BulgarianNationality {
            get {
                return ResourceManager.GetString("BulgarianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string ChineseNationality {
            get {
                return ResourceManager.GetString("ChineseNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colombian.
        /// </summary>
        internal static string ColombianNationality {
            get {
                return ResourceManager.GetString("ColombianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Costa Rican.
        /// </summary>
        internal static string CostaRicanNationality {
            get {
                return ResourceManager.GetString("CostaRicanNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string CroatianNationality {
            get {
                return ResourceManager.GetString("CroatianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Czech.
        /// </summary>
        internal static string CzechNationality {
            get {
                return ResourceManager.GetString("CzechNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danish.
        /// </summary>
        internal static string DanishNationality {
            get {
                return ResourceManager.GetString("DanishNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string DutchNationality {
            get {
                return ResourceManager.GetString("DutchNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of England.
        /// </summary>
        internal static string EnglandFederation {
            get {
                return ResourceManager.GetString("EnglandFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EnglishNationality {
            get {
                return ResourceManager.GetString("EnglishNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of France.
        /// </summary>
        internal static string FranceFederation {
            get {
                return ResourceManager.GetString("FranceFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string FrenchNationality {
            get {
                return ResourceManager.GetString("FrenchNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string GermanNationality {
            get {
                return ResourceManager.GetString("GermanNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Germany.
        /// </summary>
        internal static string GermanyFederation {
            get {
                return ResourceManager.GetString("GermanyFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goalkeeper.
        /// </summary>
        internal static string Goalkeeper {
            get {
                return ResourceManager.GetString("Goalkeeper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greek.
        /// </summary>
        internal static string GreekNationality {
            get {
                return ResourceManager.GetString("GreekNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Holland.
        /// </summary>
        internal static string HollandFederation {
            get {
                return ResourceManager.GetString("HollandFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        internal static string HungarianNationality {
            get {
                return ResourceManager.GetString("HungarianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icelandic.
        /// </summary>
        internal static string IcelandicNationality {
            get {
                return ResourceManager.GetString("IcelandicNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Irish.
        /// </summary>
        internal static string IrishNationality {
            get {
                return ResourceManager.GetString("IrishNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        internal static string ItalianNationality {
            get {
                return ResourceManager.GetString("ItalianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Italy.
        /// </summary>
        internal static string Italy_Federation {
            get {
                return ResourceManager.GetString("Italy Federation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamaican.
        /// </summary>
        internal static string JamaicanNationality {
            get {
                return ResourceManager.GetString("JamaicanNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        internal static string JapaneseNationality {
            get {
                return ResourceManager.GetString("JapaneseNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latvian.
        /// </summary>
        internal static string LatvianNationality {
            get {
                return ResourceManager.GetString("LatvianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Center Defender.
        /// </summary>
        internal static string LeftCenterDefender {
            get {
                return ResourceManager.GetString("LeftCenterDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Center Middle Forward.
        /// </summary>
        internal static string LeftCenterMiddleForward {
            get {
                return ResourceManager.GetString("LeftCenterMiddleForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Defender.
        /// </summary>
        internal static string LeftDefender {
            get {
                return ResourceManager.GetString("LeftDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Forward.
        /// </summary>
        internal static string LeftForward {
            get {
                return ResourceManager.GetString("LeftForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Middle Forward.
        /// </summary>
        internal static string LeftMiddleForward {
            get {
                return ResourceManager.GetString("LeftMiddleForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lithuanian.
        /// </summary>
        internal static string LithuanianNationality {
            get {
                return ResourceManager.GetString("LithuanianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mexican.
        /// </summary>
        internal static string MexicanNationality {
            get {
                return ResourceManager.GetString("MexicanNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nigerian.
        /// </summary>
        internal static string NigerianNationality {
            get {
                return ResourceManager.GetString("NigerianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Norwegian.
        /// </summary>
        internal static string NorwegianNationality {
            get {
                return ResourceManager.GetString("NorwegianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Poland.
        /// </summary>
        internal static string PolandFederation {
            get {
                return ResourceManager.GetString("PolandFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string PolishNationality {
            get {
                return ResourceManager.GetString("PolishNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Portugal.
        /// </summary>
        internal static string Portugal_Federation {
            get {
                return ResourceManager.GetString("Portugal Federation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portuguese.
        /// </summary>
        internal static string PortugueseNationality {
            get {
                return ResourceManager.GetString("PortugueseNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Center Defender.
        /// </summary>
        internal static string RightCenterDefender {
            get {
                return ResourceManager.GetString("RightCenterDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Center Middle Forward.
        /// </summary>
        internal static string RightCenterMiddleForward {
            get {
                return ResourceManager.GetString("RightCenterMiddleForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Defender.
        /// </summary>
        internal static string RightDefender {
            get {
                return ResourceManager.GetString("RightDefender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Forward.
        /// </summary>
        internal static string RightForward {
            get {
                return ResourceManager.GetString("RightForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Middle Forward.
        /// </summary>
        internal static string RightMiddleForward {
            get {
                return ResourceManager.GetString("RightMiddleForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romanian.
        /// </summary>
        internal static string RomanianNationality {
            get {
                return ResourceManager.GetString("RomanianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Scotland.
        /// </summary>
        internal static string ScotlandFederation {
            get {
                return ResourceManager.GetString("ScotlandFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scottish.
        /// </summary>
        internal static string ScottishNationality {
            get {
                return ResourceManager.GetString("ScottishNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slovak.
        /// </summary>
        internal static string SlovakNationality {
            get {
                return ResourceManager.GetString("SlovakNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to South African.
        /// </summary>
        internal static string SouthAfricanNationality {
            get {
                return ResourceManager.GetString("SouthAfricanNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Spain.
        /// </summary>
        internal static string SpainFederation {
            get {
                return ResourceManager.GetString("SpainFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string SpanishNationality {
            get {
                return ResourceManager.GetString("SpanishNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string SwedishNationality {
            get {
                return ResourceManager.GetString("SwedishNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swiss.
        /// </summary>
        internal static string SwissNationality {
            get {
                return ResourceManager.GetString("SwissNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Turkey.
        /// </summary>
        internal static string TurkeyFederation {
            get {
                return ResourceManager.GetString("TurkeyFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string TurkishNationality {
            get {
                return ResourceManager.GetString("TurkishNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Federation Of Ukraine.
        /// </summary>
        internal static string UkraineFederation {
            get {
                return ResourceManager.GetString("UkraineFederation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukranian.
        /// </summary>
        internal static string UkranianNationality {
            get {
                return ResourceManager.GetString("UkranianNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uruguayan.
        /// </summary>
        internal static string UruguayanNationality {
            get {
                return ResourceManager.GetString("UruguayanNationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welsh.
        /// </summary>
        internal static string WelshNationality {
            get {
                return ResourceManager.GetString("WelshNationality", resourceCulture);
            }
        }
    }
}
