CREATE TABLE [dbo].[Transfer]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
    [PlayerId] UNIQUEIDENTIFIER NOT NULL, 
    [SellTeamId] UNIQUEIDENTIFIER NOT NULL, 
    [BuyTeamId] UNIQUEIDENTIFIER NOT NULL, 
    [Price] DECIMAL NOT NULL, 
    [TransferDate] DATETIME NOT NULL
)
